# Generated by Django 6.0 on 2025-12-16 14:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0004_alter_event_event_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('is_private', models.BooleanField(default=False)),
                ('upload_time_stamp', models.DateTimeField(auto_now_add=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('gps_latitude', models.FloatField(blank=True, null=True)),
                ('gps_longitude', models.FloatField(blank=True, null=True)),
                ('camera_model', models.CharField(blank=True, max_length=100, null=True)),
                ('aperture', models.CharField(blank=True, max_length=100, null=True)),
                ('shutter_speed', models.CharField(blank=True, max_length=100, null=True)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='event.event')),
            ],
            options={
                'ordering': ['-taken_at', '-upload_time_stamp'],
            },
        ),
    ]
