# Generated by Django 6.0 on 2025-12-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='event_name',
            new_name='event_id',
        ),
    ]
