# Generated by Django 6.0 on 2026-01-24 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='downloaded_by',
        ),
        migrations.AddField(
            model_name='photo',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PhotoDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['downloaded_at'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='downloaded',
            field=models.ManyToManyField(blank=True, related_name='downloaded_photos', through='photo.PhotoDownload', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='photodownload',
            index=models.Index(fields=['photo', 'user'], name='photo_photo_photo_i_295980_idx'),
        ),
        migrations.AddIndex(
            model_name='photodownload',
            index=models.Index(fields=['downloaded_at'], name='photo_photo_downloa_dec8bf_idx'),
        ),
    ]
