# Generated by Django 6.0 on 2026-01-24 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_remove_photo_downloaded_by_photo_view_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='photodownload',
            name='photo_photo_photo_i_295980_idx',
        ),
        migrations.RemoveIndex(
            model_name='photodownload',
            name='photo_photo_downloa_dec8bf_idx',
        ),
        migrations.AddField(
            model_name='photodownload',
            name='download_type',
            field=models.CharField(choices=[('original', 'Original'), ('watermark', 'Watermarked')], default='original', max_length=10),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='photodownload',
            index=models.Index(fields=['user', 'download_type', 'downloaded_at'], name='photo_photo_user_id_484a34_idx'),
        ),
    ]
