# Generated by Django 6.0 on 2025-12-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_rename_event_name_photo_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='event_id',
            new_name='event',
        ),
    ]
