# Generated by Django 6.0 on 2026-01-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_remove_photodownload_photo_photo_photo_i_295980_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photodownload',
            name='download_type',
            field=models.CharField(choices=[('original', 'Original'), ('watermarked', 'Watermarked')], max_length=11),
        ),
    ]
