# Generated by Django 6.0 on 2025-12-17 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_photo_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tagged_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='tagged_In', to=settings.AUTH_USER_MODEL),
        ),
    ]
