# Generated by Django 6.0 on 2025-12-19 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_phototag_tag_photo_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('like_time_stamp', models.DateTimeField(auto_now_add=True)),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.photo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PhotoTag',
        ),
        migrations.AddField(
            model_name='photo',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_photos', through='photo.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
