# Generated by Django 6.0 on 2025-12-12 13:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('qr_code_url', models.TextField(blank=True, null=True)),
                ('event_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinated_events', to=settings.AUTH_USER_MODEL)),
                ('event_members', models.ManyToManyField(related_name='participated_events', to=settings.AUTH_USER_MODEL)),
                ('event_photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_as_photographer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
    ]
