# Generated by Django 6.0 on 2025-12-12 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_qr_code_url_event_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2025, 12, 12, 21, 5, 36, 613984, tzinfo=datetime.timezone.utc), unique=True),
            preserve_default=False,
        ),
    ]
