# Generated by Django 6.0 on 2025-12-12 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_members',
            field=models.ManyToManyField(blank=True, null=True, related_name='participated_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
