# Generated by Django 6.0 on 2026-01-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-send_time']},
        ),
    ]
